// utils
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADMORE = 'SET_LOADMORE';
export const SET_LOADING_UPLOAD = 'SET_LOADING_UPLOAD';
export const SET_LOADING_API = 'SET_LOADING_API';
export const SET_LOADING_GET_POSTS = 'SET_LOADING_GET_POSTS';
export const SET_ERROR = 'SET_ERROR';

// auth
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// user
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SET_LIST_FOLLOW = 'SET_LIST_FOLLOW';

// post
export const CREATE_DISCUSSION = 'CREATE_DISCUSSION';

// stream
export const SET_STREAM = 'SET_STREAM';
export const SET_TRENDING_AUDIOS = 'SET_TRENDING_AUDIOS';

// post
export const SET_DISCUSSIONS = 'SET_DISCUSSIONS';
export const LOAD_MORE_DISCUSSIONS = 'LOAD_MORE_DISCUSSIONS'

export const SET_BLOGS = 'SET_BLOGS';
export const SET_BOOK_REVIEWS = 'SET_BOOK_REVIEWS';
export const SET_MOVIE_REVIEWS = 'SET_MOVIE_REVIEWS';
export const SET_FOOD_REVIEWS = 'SET_FOOD_REVIEWS';
export const SET_SONGS = 'SET_SONGS';
export const SET_PODCASTS = 'SET_PODCASTS';
export const LOAD_MORE_PODCASTS = 'LOAD_MORE_PODCASTS';

// player
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_PLAYING_PAUSE = 'UPDATE_PLAYING_PAUSE';
export const TOGGLE_SHOW_PLAYER = 'TOGGLE_SHOW_PLAYER';
export const SWITCH_AUDIO = 'SWITCH_AUDIO';
export const HANDLE_LIST_SWITCH = 'HANDLE_LIST_SWITCH';

// tag
export const SET_POSTS_BY_TAGS = 'SET_POSTS_BY_TAGS';
export const LOAD_MORE_POST_BY_TAGS = 'LOAD_MORE_POST_BY_TAGS';

// notification
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const LOADMORE_NOTIFICATIONS = 'LOADMORE_NOTIFICATIONS';
export const DELETE_ALL_NOTIFICATIONS = 'DELETE_ALL_NOTIFICATIONS';
export const TOGGLE_SHOW_NOTIF_LIST = 'TOGGLE_SHOW_NOTIF_LIST';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const MARK_ALL_AS_READ = 'MARK_ALL_AS_READ';
export const MARK_ONE_AS_READ = 'MARK_ONE_AS_READ';
